# Generated by Django 4.1.7 on 2023-04-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('first_name',)},
        ),
    ]
