# Generated by Django 4.1.7 on 2023-03-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founded', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
