# Generated by Django 4.1.7 on 2023-04-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('country_abbreviation', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('country', 'circuit_name'),
            },
        ),
    ]
