# Generated by Django 4.1.7 on 2023-04-13 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('core', '0002_racetrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField()),
                ('race_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_prix', to='core.racetrack')),
            ],
            options={
                'ordering': ('race_date',),
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('13th', '13th'), ('14th', '14th'), ('15th', '15th'), ('16th', '16th'), ('17th', '17th'), ('18th', '18th'), ('19th', '19th'), ('20th', '20th')], max_length=4, unique_for_date='grand_prix__race_date')),
                ('retired', models.BooleanField(default=False)),
                ('fastest_lap', models.BooleanField(default=False, unique_for_date='grand_prix__race_date')),
                ('points', models.IntegerField()),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='core.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raceresults', to='driver.driver')),
                ('grand_prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='core.grandprix')),
            ],
            options={
                'ordering': ('grand_prix__race_date', 'points'),
            },
        ),
    ]
