# Generated by Django 4.1.7 on 2023-04-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_grandprix_options_alter_raceresult_fastest_lap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='points',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
