# Generated by Django 4.1.7 on 2023-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_raceresult_options_alter_raceresult_finish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceresult',
            options={'ordering': ('-grand_prix__race_date', '-points', 'position')},
        ),
        migrations.RenameField(
            model_name='raceresult',
            old_name='finish',
            new_name='position',
        ),
        migrations.AddConstraint(
            model_name='raceresult',
            constraint=models.UniqueConstraint(fields=('grand_prix', 'position'), name='unique_constraint_race_and_position'),
        ),
    ]
