# Generated by Django 4.1.7 on 2023-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_raceresult_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='raceresult',
            constraint=models.UniqueConstraint(fields=('grand_prix', 'driver', 'position'), name='unique_constraint_race_and_driver_and_position'),
        ),
    ]
