# Generated by Django 4.1.7 on 2023-04-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_raceresult_unique_constraint_race_and_driver_and_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='raceresult',
            name='unique_constraint_race_and_driver_and_position',
        ),
        migrations.AddConstraint(
            model_name='raceresult',
            constraint=models.UniqueConstraint(fields=('grand_prix', 'driver'), name='unique_constraint_race_and_driver_and_position'),
        ),
    ]
